"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, LoaderCircle, LockKeyhole } from "lucide-react";
import { createCase } from "../../lib/api";

const initial = { company_name: "", website: "", sector: "", funding_stage: "Pre-seed", funding_requested: "", github_url: "", monthly_revenue: "", monthly_burn: "", cash_available: "", customers: "" };
export default function NewCase() {
  const [values, setValues] = useState(initial); const [deck, setDeck] = useState<File | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  const change = (key: keyof typeof initial, value: string) => setValues((old) => ({ ...old, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const num = (value: string) => value.trim() ? Number(value) : null; const payload = { company_name: values.company_name, website: values.website || null, sector: values.sector, funding_stage: values.funding_stage, funding_requested: num(values.funding_requested), github_url: values.github_url || null, financial_inputs: { monthly_revenue: num(values.monthly_revenue), monthly_burn: num(values.monthly_burn), cash_available: num(values.cash_available), customers: num(values.customers) } }; const result = await createCase(payload, deck); router.push(`/cases/${result.case_id}/analysis`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not start diligence."); } finally { setLoading(false); } }
  return <main className="shell py-10"><Link className="eyebrow" href="/">← DealLens AI</Link><div className="mt-12 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><section><p className="eyebrow">New diligence case</p><h1 className="mt-3 text-5xl tracking-tight">Bring the operating facts.</h1><p className="mt-5 leading-7 text-slate-400">The agent system distinguishes public evidence from founder-provided context and unavailable sources.</p><p className="mt-8 flex gap-2 text-sm text-slate-400"><LockKeyhole size={17} className="text-cyan-300"/> API credentials remain on the backend.</p></section><form className="glass grid gap-5 p-7 md:grid-cols-2" onSubmit={submit}>{[["company_name","Startup name", "Aperture Labs",true],["website","Website", "https://example.com",false],["sector","Industry", "Climate software",true],["funding_requested","Funding request", "750000",false],["github_url","GitHub URL", "https://github.com/org/repo",false],["monthly_revenue","Monthly revenue", "18000",false],["monthly_burn","Monthly burn", "42000",false],["cash_available","Cash available", "510000",false],["customers","Customers", "15",false]].map(([key,label,placeholder,required])=><div key={key as string}><label>{label as string}</label><input required={required as boolean} type={String(key).includes("monthly") || ["funding_requested","cash_available","customers"].includes(key as string) ? "number" : "url" === key ? "url" : "text"} value={values[key as keyof typeof initial]} onChange={e=>change(key as keyof typeof initial,e.target.value)} placeholder={placeholder as string}/></div>)}<div><label>Stage</label><select value={values.funding_stage} onChange={e=>change("funding_stage",e.target.value)}><option>Pre-seed</option><option>Seed</option><option>Series A</option><option>Series B+</option></select></div><div><label>Pitch deck PDF (optional · max 10 MB)</label><input type="file" accept="application/pdf" onChange={e=>setDeck(e.target.files?.[0] ?? null)}/></div>{error && <p className="md:col-span-2 rounded border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<button disabled={loading} className="button md:col-span-2 justify-center disabled:opacity-60" type="submit">{loading ? <><LoaderCircle className="animate-spin" size={17}/> Starting workflow</> : <>Run Due Diligence <ArrowRight size={17}/></>}</button></form></div></main>
}
